parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5433
    database_name:     expresso
    database_user:     postgres
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    memcached.servers:
      - { host: 127.0.0.1, port: 11211 }
