jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Expresso\ExpressoBundle\User\LdapUser:
            algorithm: md5
            encode-as-base64: true
            iterations: 0

  #  role_hierarchy:
  #      ROLE_ADMIN:       ROLE_USER
   #     ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ldap:
            id: Expresso.Ldap.UserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|template|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        setup:
            pattern:  ^/setup
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: Expresso.Ldap.login_handler
            logout:
                path:   /logout
                target: /
                success_handler: Expresso.Ldap.login_handler
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"



    access_control:
       # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        # You can omit this if /api can be accessed both authenticated and anonymously
        #- { path: /rest/Mail, roles: [ ROLE_MAIL_ACCESS ] }
