parameters:
#    app_manager.example.class: Expresso\AppManagerBundle\Example

services:
#    app_manager.example:
#        class: %app_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
