ExpressoSetupBundle_homepage:
    pattern:  /{index}
    defaults: { _controller: SetupBundle:Default:setup, index: 0 }

ExpressoSetupBundle_setup:
    pattern:  /{index}
    defaults: { _controller: SetupBundle:Default:setup, index: 0 }

ExpressoSetupBundle_final:
    pattern:  /final/
    defaults: { _controller: SetupBundle:Default:final }

ExpressoSetupBundle_check:
    pattern: /check/
    defaults: {_controller: SetupBundle:Default:checkEnviroment}