parameters:
#    expresso.example.class: Expresso\ExpressoBundle\Example

services:
#    expresso.example:
#        class: %expresso.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
